#Run and build gerald77/debian-ssh-borgbackup

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'gerald77/debian-ssh-borgbackup'
  dockerHub: 'gerald77'

steps:
- task: Docker@2
  displayName: Build debian-ssh-borgbackup
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile
    tags: latest
- task: Docker@2
  displayName: Push debian-ssh-borgbackup
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: latest